# <center>k Nearest Neighbours</center>

## <center>Import libraries</center>

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

## <center>Import dataset</center>

In [2]:
dataset = pd.read_csv("Social_Network_Ads.csv")
X = dataset.iloc[ : , : -1].values
y = dataset.iloc[ : , -1].values

## <center>Splitting dataset into training and testing</center>

In [3]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, 
                                                    test_size = 0.1, 
                                                    random_state = 0)

In [4]:
print(X_train, end = "\n\n\n")
print(X_test)
print(y_train)
print(y_test, end = "\n")

[[    27  88000]
 [    41  52000]
 [    27  84000]
 [    35  20000]
 [    43 112000]
 [    27  58000]
 [    37  80000]
 [    52  90000]
 [    26  30000]
 [    49  86000]
 [    57 122000]
 [    34  25000]
 [    35  57000]
 [    34 115000]
 [    59  88000]
 [    45  32000]
 [    29  83000]
 [    26  80000]
 [    49  28000]
 [    23  20000]
 [    32  18000]
 [    60  42000]
 [    19  76000]
 [    36  99000]
 [    19  26000]
 [    60  83000]
 [    24  89000]
 [    27  58000]
 [    40  47000]
 [    42  70000]
 [    32 150000]
 [    35  77000]
 [    22  63000]
 [    45  22000]
 [    27  89000]
 [    18  82000]
 [    42  79000]
 [    40  60000]
 [    53  34000]
 [    47 107000]
 [    58 144000]
 [    59  83000]
 [    24  55000]
 [    26  35000]
 [    58  38000]
 [    42  80000]
 [    40  75000]
 [    59 130000]
 [    46  41000]
 [    41  60000]
 [    42  64000]
 [    37 146000]
 [    23  48000]
 [    25  33000]
 [    24  84000]
 [    27  96000]
 [    23  63000]
 [    48  33000]
 [    48  9000

## <center>Feature Scaling</center>

In [5]:
from sklearn.preprocessing import StandardScaler

standard_scaler = StandardScaler()
X_train = standard_scaler.fit_transform(X_train)
X_test = standard_scaler.transform(X_test)

In [6]:
print("X_train = \n", X_train)
print("\n\n\n")
print("X_test = \n", X_test)

X_train = 
 [[-1.05714987  0.53420426]
 [ 0.2798728  -0.51764734]
 [-1.05714987  0.41733186]
 [-0.29313691 -1.45262654]
 [ 0.47087604  1.23543867]
 [-1.05714987 -0.34233874]
 [-0.10213368  0.30045946]
 [ 1.33039061  0.59264046]
 [-1.15265148 -1.16044554]
 [ 1.04388575  0.47576806]
 [ 1.8078987   1.52761967]
 [-0.38863853 -1.30653604]
 [-0.29313691 -0.37155684]
 [-0.38863853  1.32309297]
 [ 1.99890194  0.53420426]
 [ 0.66187928 -1.10200934]
 [-0.86614663  0.38811376]
 [-1.15265148  0.30045946]
 [ 1.04388575 -1.21888174]
 [-1.43915634 -1.45262654]
 [-0.57964177 -1.51106275]
 [ 2.09440356 -0.80982834]
 [-1.82116282  0.18358706]
 [-0.19763529  0.85560337]
 [-1.82116282 -1.27731794]
 [ 2.09440356  0.38811376]
 [-1.34365472  0.56342236]
 [-1.05714987 -0.34233874]
 [ 0.18437118 -0.66373784]
 [ 0.37537442  0.00827846]
 [-0.57964177  2.34572647]
 [-0.29313691  0.21280516]
 [-1.53465796 -0.19624824]
 [ 0.66187928 -1.39419034]
 [-1.05714987  0.56342236]
 [-1.91666444  0.35889566]
 [ 0.37537442  0

## <center>Training the model</center>

In [7]:
from sklearn.neighbors import KNeighborsClassifier

knn_classifier = KNeighborsClassifier()
knn_classifier.fit(X_train, y_train)

KNeighborsClassifier()

## <center>Predicting values</center>

In [9]:
y_pred = knn_classifier.predict(X_test)
print("y_pred\ty_test")
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

y_pred	y_test
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]]


## <center>Confusion matrix</center>

In [10]:
from sklearn.metrics import accuracy_score, confusion_matrix

confusion_matrix_obj = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", confusion_matrix_obj)
print("Accuracy score:\t", accuracy_score(y_test, y_pred))

Confusion Matrix:
 [[30  2]
 [ 1  7]]
Accuracy score:	 0.925


## <center>Training model with parameters</center>

In [11]:
from sklearn.neighbors import KNeighborsClassifier

knn_classifier_2 = KNeighborsClassifier(n_neighbors = 5, metric = 'minkowski', p = 2)
knn_classifier_2.fit(X_train, y_train)

KNeighborsClassifier()

## <center>Predicting values</center>

In [12]:
y_pred_2 = knn_classifier.predict(X_test)
print("y_pred\ty_test")
print(np.concatenate((y_pred_2.reshape(len(y_pred_2), 1), 
                      y_test.reshape(len(y_test), 1)), 1))

y_pred	y_test
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]]


## <center>Confusion Matrix</center>

In [13]:
from sklearn.metrics import accuracy_score, confusion_matrix

confusion_matrix_obj_2 = confusion_matrix(y_test, y_pred_2)
print("Confusion Matrix:\n", confusion_matrix_obj_2)
print("Accuracy score:\t", accuracy_score(y_test, y_pred_2))

Confusion Matrix:
 [[30  2]
 [ 1  7]]
Accuracy score:	 0.925
