# **Artificial Neural Network** (Practical 7)

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__


'2.9.1'

In [3]:
dataset=pd.read_csv('E:\Machine Learning\Datasets\Churn_Modelling.csv')
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values

In [4]:
print(x)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
x[:,2]=le.fit_transform(x[:,2])

In [7]:
print(x)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct=ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
x=np.array(ct.fit_transform(x))

In [9]:
print(x)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [10]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=0)


In [11]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [12]:
ann=tf.keras.models.Sequential()


In [13]:
ann.add(tf.keras.layers.Dense(units=6 ,activation="relu"))    #input layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6 ,activation="relu"))    #hidden layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))   #output layer

In [16]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [17]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 9s 1ms/step - loss: 0.5553 - accuracy: 0.7929
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4850 - accuracy: 0.7972
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4448 - accuracy: 0.8089
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4235 - accuracy: 0.8181
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4093 - accuracy: 0.8229
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3979 - accuracy: 0.8260
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3878 - accuracy: 0.8301
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3784 - accuracy: 0.8338
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3705 - accuracy: 0.8464
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3638 - accura

In [18]:
print(ann.predict(sc.transform([[1,0,0,600,1,40,3,60000,2,1,1,50000]]))>0.5)

1/1 [==============================] - 0s 383ms/step
[[False]]


In [19]:
y_pred=ann.predict(x_test)
y_pred=(y_pred>0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

63/63 [==============================] - 0s 974us/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [20]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1517   78]
 [ 202  203]]


0.86